dive_into/crm/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth.decorators import login_required
app_name = 'crm'

urlpatterns = [
    url(r'^$', views.MainPage.as_view(), name='main'),

    url(r'clients/$', views.Clients.as_view(), name='clients'),
    url(r'^clients/(?P<pk>[0-9]+)/$', views.DistinctClient.as_view(), name='client'),
    url(r'^clients/create', login_required(views.CreateClient.as_view()), name='new_client'),

    url(r'^contacts/$', views.Contacts.as_view(), name='contacts'),
    url(r'^contacts/(?P<pk>[0-9]+)/$', views.DistinctContact.as_view(), name='contact'),
    url(r'contacts/create', login_required(views.CreateContact.as_view()), name='new_contact'),

    url(r'^activities/$', views.Activities.as_view(), name='activities'),
    url(r'^activities/(?P<pk>[0-9]+)/$', views.DistinctActivity.as_view(), name='activity'),
    url(r'activities/create', login_required(views.CreateActivity.as_view()), name='new_activity')
]

dive_into/dive_into/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth.views
from . import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^crm/', include('crm.urls', namespace='crm')),

    url('^register/', views.UserCreate.as_view(), name='register'),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, {'next_page': '/crm'}, name='logout')
]

dive_into/crm/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class Client(models.Model):
    """
    Таблица с данными о всех клиентах, с пометкой о их лояльности
    Связь с таблицами Contact и Activity
    """
    name = models.CharField(max_length=200, unique=True)
    loyal = models.BooleanField(default=False)
    owner = models.ForeignKey(User, editable=True, null=True, blank=True)

    def last_activity(self):
        send_dates = [i.send_date for i in self.activity_set.all() if i.is_send()]

        last = max(send_dates).strftime("%Y.%m.%d %H:%M") if send_dates else None
        return last

    def str_with_html(self):
        return u'<b>Name</b>: {}\n<b>Loyal</b>: {}\n<b>Id</b>: {}'.format(self.name,
                                                                          self.loyal,
                                                                          self.id)

    def __unicode__(self):
        return u'Name: {}, Id: {}'.format(self.name, self.id)


class Contact(models.Model):
    """
    Таблица с данными о всех контактах в системе
    """
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.IntegerField()
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)
    active = models.BooleanField(default=True)
    owner = models.ForeignKey(User, editable=True, null=True)

    def full_name(self):
        return u'{} {}'.format(self.first_name, self.last_name)

    def str_with_html(self):
        template = u'''<b>First name</b>: {}\n<b>Last name</b>: {}\n<b>Email</b>: {}
        <b>Phone</b>: {}\n<b>Active</b>: {}\n<b>Client</b>: {}\n'''
        return template.format(self.first_name, self.last_name,
                               self.email, str(self.phone),
                               str(self.active), self.client.name if self.client else '--')

    def __unicode__(self):
        template = u'First name: {}, Email: {}, Client id: {}'
        return template.format(self.first_name, self.email, self.client.id if self.client else '--')


class Activity(models.Model):
    """
    Таблица с данными о всех активностях в системе, в каждой активности должен быть
    указан клиент и соответствующий контакт
    """

    title = models.CharField(max_length=30)
    text = models.CharField(max_length=10000)
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    contact = models.ForeignKey(Contact, on_delete=models.PROTECT, limit_choices_to={'active': True})
    send_date = models.DateTimeField(null=True, blank=True)
    owner = models.ForeignKey(User, editable=True, null=True)

    def send(self):
        self.send_date = timezone.now()

    def is_send(self):
        return self.send_date is not None

    def str_with_html(self):
        send_date = self.send_date.strftime("%Y.%m.%d %H:%M") if self.send_date else u'Нет'
        return u'<b>Client</b>: {}\n <b>From</b>: {}\n<b>Title</b>: {}\n<b>Send date</b>: {}'.format(self.client.name,
                                                                                                     self.contact.email,
                                                                                                     self.title,
                                                                                                     send_date)

    def __unicode__(self):
        send_date = self.send_date if self.send_date else u'Нет'
        return u'Клиент: {}, Тема: {}, Отправлено: {}'.format(self.client.name, self.title, send_date)

dive_into/crm/forms.py
# coding=utf-8
from django import forms
from .models import Client, Contact, Activity


class ContactCreation(forms.ModelForm):
    def __init__(self, user=None, *args, **kwargs):
        super(ContactCreation, self).__init__(*args, **kwargs)
        self.fields['client'].queryset = Client.objects.filter(owner=user)

    class Meta:
        model = Contact

        fields = ('first_name',
                  'last_name',
                  'email',
                  'phone',
                  'client',
                  'active')


class ClientCreation(forms.ModelForm):

    class Meta:
        model = Client
        fields = ('name', 'loyal')


class ActivityCreation(forms.ModelForm):
    def __init__(self, user=None, *args, **kwargs):
        super(ActivityCreation, self).__init__(*args, **kwargs)
        self.user = user
        user_clients = Client.objects.filter(owner=self.user)
        self.fields['client'].queryset = user_clients
        self.fields['contact'].queryset = Contact.objects.filter(client__in=user_clients)

    def clean(self):
        super(ActivityCreation, self).clean()
        form_data = self.cleaned_data
        if all((form_data.get('client', ''), form_data.get('contact', ''))) \
                and form_data['client'] != form_data['contact'].client:

            del form_data['contact']
            del form_data['client']
            raise forms.ValidationError("Chosen contact doesn't belong to chosen client")
        elif self.instance.send_date:
            raise forms.ValidationError("You can't change activity which was sent")
        return form_data

    class Meta:
        model = Activity
        fields = ('title',
                  'text',
                  'client',
                  'contact')

        widgets = {
            'text': forms.Textarea(),
        }

dive_into/crm/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.views import generic
from django.core.urlresolvers import reverse
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied

from .models import Client, Contact, Activity
from .forms import ContactCreation, ClientCreation, ActivityCreation


class NoOwnerError(Exception):
    pass


class MainPage(generic.View):
    """
    Отвечает за отображение главной страницы системы,
    поддверживает получение get запросов с указанным именем клиента для поиска
    и отображения
    """
    template = 'crm/main.html'
    model = Client

    def get(self, request):
        context = {}
        if request.GET.get('search', None):
            if self.request.user.is_authenticated():
                clients = self.model.objects.filter(name__icontains=request.GET.get('search', ''),
                                                    owner=request.user)

                if clients:
                    context['search_clients'] = clients
                else:
                    context['search_clients'] = 'no result'
            else:
                context['search_clients'] = 'no auth'

        elif request.session.get('deleted_data', ''):
            context['deleted_data'] = request.session['deleted_data']
            request.session['deleted_data'] = None

        return render(request, self.template, context)


class Distinct(generic.UpdateView):
    """
    Класс для наследования UpdateView + обработка нажатия кнопки Delete на странице
    с удалением соответствующего объекта, если нет препятствий
    """

    def dispatch(self, *args, **kwargs):
        try:
            return super(Distinct, self).dispatch(*args, **kwargs)
        except NoOwnerError:
            return redirect(reverse('crm:{}'.format(self.distinct_template), kwargs={'pk': self.kwargs['pk']}))

    def get_object(self, queryset=None):
        try:
            object_get = self.model.objects.get(pk=self.kwargs['pk'])
        except ObjectDoesNotExist:
            raise Http404("No object found matching this query")

        if self.request.user.is_authenticated():
            if object_get.owner == self.request.user:
                return object_get

    def get_form_kwargs(self):
        """
        Добавляем текущего пользователя в список аргументов,
        для корректного формирования списка foreign_keys's
        доступных для выбора
        """
        kwargs = super(Distinct, self).get_form_kwargs()
        if self.request.user.is_authenticated():
            kwargs.update({'user': self.request.user})
        return kwargs

    def post(self, request, *args, **kwargs):
        object_get = self.get_object()
        if not object_get:
            """
            Если объект не найден - значит текущий пользователь
            не является владельцем объекта, который пытается изменить,
            выбрасываем ошибку
            """
            raise NoOwnerError
        if request.POST.get('action', '') == 'Delete':
            request.session['deleted_data'] = str(object_get)
            object_get.delete()
            return redirect(reverse('crm:main'))
        else:
            return super(Distinct, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('crm:{}'.format(self.distinct_template), kwargs={'pk': self.kwargs['pk']})


class Creation(generic.CreateView):
    """
    Класс для наследования CreateView + передача текущего пользователя в
    форму для заполнения поля owner в соответствующей модели
    """
    def get_form_kwargs(self):
        """
        Добавляем текущего пользователя в список аргументов,
        для корректного формирования списка foreign_keys's
        доступных для выбора
        """
        kwargs = super(Creation, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('crm:{}'.format(self.url), kwargs={'pk': self.object.id})

    def form_valid(self, form):
        object_to_save = form.save(commit=False)
        object_to_save.owner = self.request.user
        return super(Creation, self).form_valid(form)


class List(generic.ListView):
    def get_queryset(self):
        if self.request.user.is_authenticated():
            return self.model.objects.filter(owner=self.request.user)


class Clients(List):
    """
    Отображает список всех клиентов в системе
    """
    model = Client
    template_name = 'crm/clients.html'
    context_object_name = 'clients_list'


class DistinctClient(Distinct):
    """
    Отображает информацию по клиенту, позволяет редактировать
    информацию клиента, а так же удалять его
    """
    form_class = ClientCreation
    model = Client
    template_name = 'crm/client_detail.html'
    all_template = 'clients'
    distinct_template = 'client'

    def get_form_kwargs(self):
        """
        Переписываем родительский метод Distinct, так
        как для создания клиента нет нужды фильтровать
        доступные результаты в форме для foreing_keys
        """
        return generic.UpdateView.get_form_kwargs(self)


class CreateClient(Creation):
    """
    Обрабатывает запросы на создание клиента,
    при успехе перекидывает на страницу созданного клиента
    """
    form_class = ClientCreation
    template_name = 'crm/new_client.html'
    url = 'client'

    def get_form_kwargs(self):
        """
        Переписываем родительский метод Creation, так
        как для создания клиента нет нужды фильровать
        доступные результаты в форме для foreing_keys
        """
        return generic.CreateView.get_form_kwargs(self)


class Contacts(List):
    """
    Отображает список всех контактов в системе
    """
    model = Contact
    template_name = 'crm/contacts.html'
    context_object_name = 'contacts_list'


class DistinctContact(Distinct):
    """
    Отображает информацию по контакту, позволяет редактировать
    информацию контакта, а так же удалять его
    """
    form_class = ContactCreation
    model = Contact
    template_name = 'crm/contact_detail.html'
    all_template = 'contacts'
    distinct_template = 'contact'


class CreateContact(Creation):
    """
    Обрабатывает запросы на создание контакта,
    при успехе перекидывает на страницу созданного контакта
    """
    form_class = ContactCreation
    template_name = 'crm/new_contact.html'
    url = 'contact'


class Activities(List):
    """
    Отображает список всех активностей в системе
    """
    model = Activity
    template_name = 'crm/activities.html'
    context_object_name = 'activities_list'


class DistinctActivity(Distinct):
    """
    Отображает информацию по активности, позволяет редактировать
    информацию о активности, а так же удалять ее, при этом удаление и
    редактирование доступны только для не отправленных активностей,
    если активность отправлена - такой возможности не предоставляется
    """
    form_class = ActivityCreation
    model = Activity
    template_name = 'crm/activity_detail.html'
    all_template = 'activities'
    distinct_template = 'activity'

    def post(self, request, *args, **kwargs):
        if request.POST.get('action', '') == 'Send':
            activity = self.get_object()
            activity.send()
            activity.save()
            return redirect(reverse('crm:activity', kwargs={'pk': activity.id}))
        else:
            return super(DistinctActivity, self).post(request, *args, **kwargs)


class CreateActivity(Creation):
    """
    Обрабатывает запросы на создание активности,
    при успехе перекидывает на страницу созданной активности
    """
    form_class = ActivityCreation
    template_name = 'crm/new_activity.html'
    url = 'activity'

dive_into/crm/templates/crm/activities.html
{% extends 'crm/base.html' %}
{% block content %}

<p><a class="btn btn-xs btn-success" href="{% url 'crm:new_activity'%}">{{ "Create new activity" }}</a></p>

<div class="col-md-9 ">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Table of activities</h3>
    </div>
    <div class="panel-body">
      {% if activities_list %}
      <!-- Таблица всех активностей в системе -->
        <table id="contacts_table" class="table table-striped">
          <thead>
            <tr>
              <th>Client</th>
              <th>Title</th>
              <th>Contact</th>
              <th>Send date</th>
              <th>More info</th>

            </tr>
          </thead>
          <tbody>
            {% for activity in activities_list %}
            <tr>
              <td><a href="{% url 'crm:client' activity.client.id%}">{{ activity.client.name }}</a></td>
              <td> {{ activity.title }}</td>
              <td><a href="{% url 'crm:contact' activity.contact.id%}">{{ activity.contact.email }}</a></td>
              <td> {{ activity.send_date|date:"Y.m.d H:i"}}</td>
              <td><a href="{% url 'crm:activity' activity.id%}">Show</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
      <p>No activities are available.</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}

dive_into/crm/templates/crm/activity_detail.html
{% extends 'crm/base.html' %}
{% block content %}
{% load bootstrap %}
{% if activity %}
{% if not activity.is_send %}
<button class="btn btn-s btn-info" data-toggle="collapse" data-target="#hide-me">Change activity</button>
{% endif %}
<a href="{% url 'crm:client' activity.client.id%}" class="btn btn-s btn-info">{{ "Go to client" }}</a>
<a href="{% url 'crm:contact' activity.contact.id%}" class="btn btn-s btn-info">{{ "Go to contact" }}</a>
{% if not activity.is_send %}
<!-- По нажатию на кнопку проставит дату отправки активности = сейчас
  после этого редактирование активности будет невозможно-->
<form  method="post" >
  {% csrf_token %}
  <input id="action_id" type="hidden" name="action" value="Send">
  <input type="submit" value="Send" class="btn btn-s btn-warning" onclick="return confirm('Are you sure?')"/>
</form>
<!-- Удаляет не отправленную активность -->
<form  method="post">
  {% csrf_token %}
  <input id="action_id" type="hidden" name="action" value="Delete">
  <input type="submit" value="Delete" onclick="return confirm('Are you sure?')" class="btn btn-s btn-danger"/>
</form>
<div id="hide-me" class="collapse">
  <!-- Форма для изменения не отправленной активности -->
  <form method="post" class="form-horizontal">
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}
    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" value="Save changes" class="btn btn-s btn-success">
      </div>
    </div>
  </form>
</div>
{% endif %}
{% for a,b in form.errors.items %}
<div class="alert alert-danger custom-alert" role="alert">
  <strong>Warning!</strong> {{b}} You should correct the mistakes and then save changes again
</div>
{% endfor %}
<h3>{{ "Activity" }}</h3>
<blockquote>
  {{activity.str_with_html|safe|linebreaks}}
</blockquote>
<button class="btn btn-s btn-info" data-toggle="collapse" data-target="#hide-me2">View activity text</button>
<div id="hide-me2" class="collapse">
  <div style="width: 800px; height: 150px; overflow-y: scroll;">
    {{activity.text}}
  </div>
</div>
{% else %}
<h3>You don't have rights to view this activity</h3>
{% endif %}
{% endblock content %}

dive_into/crm/templates/crm/base.html
{% load staticfiles %}
{% load bootstrap %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>CRM</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <script src="{% static 'crm/java_code.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'crm/style.css' %}" type="text/css">
  </head>
  <body>
    <div class="page-header">
      <div  align="right" id="head-auth">
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-log-out"></span></a>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-log-in"></span></a>
          <a href="{% url 'register' %}" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-user"></span></a>
        {% endif %}
      </div>
      <h1><a href="{% url 'crm:main' %}" id="head_link"> CRM </a></h1>
      <a href="{% url 'crm:clients' %}" class="btn btn-lg btn-primary" >Clients</a>
      <a href="{% url 'crm:contacts' %}" class="btn btn-lg btn-primary" >Contacts</a>
      <a href="{% url 'crm:activities' %}" class="btn btn-lg btn-primary" >Activities</a>
      {% if user.is_authenticated %}
        <h5>Current user: {{user.username}}</h5>
      {% else %}
        <h5>You should log in to be able to view the data</h5>
      {% endif %}
    </div>
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

dive_into/crm/templates/crm/client_detail.html
{% extends 'crm/base.html' %}
{% block content %}
{% load bootstrap %}
{% if client %}
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#menu1">Client Info</a></li>
  <li><a data-toggle="tab" href="#menu2">Client Activities</a></li>
</ul>
<div class="tab-content">
  <div id="menu1" class="tab-pane active">
    <br>
    <button class="btn btn-s btn-info" data-toggle="collapse" data-target="#hide-me">Change client</button>
    <a href="{% url 'crm:new_activity'%}" class="btn btn-s btn-success">{{ "Create new activity" }}</a>
    <a href="{% url 'crm:new_contact'%}" class="btn btn-s btn-success">{{ "Create new contact" }}</a>

    <!-- Форма для удаление клиента -->
    <form  method="post">
      {% csrf_token %}
      <input id="action_id" type="hidden" name="action" value="Delete">
      <input type="submit" value="Delete" class="btn btn-s btn-danger" onclick="return confirm('Are you sure?')"/>
    </form>
    <div id="hide-me" class="collapse">
      <br>

      <!-- Форма для изменения данных клиента -->
      <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <br>
        <input type="submit" value="Save changes" class="btn btn-s btn-success">
      </form>

    </div>
    {% for a,b in form.errors.items %}
        <div class="alert alert-danger custom-alert" role="alert">
         <strong>Warning!</strong> {{b}} You should correct the mistakes and then save changes again
        </div>
    {% endfor %}
    <h3>Client</h3>
      <blockquote>
        {{client.str_with_html|safe|linebreaks}}
      </blockquote>

    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Client contacts</h3>
        </div>
        <div class="panel-body">
            {% if client.contact_set.all %}
              <ol>
            {% for contact in client.contact_set.all %}
              <li><b>Name</b>: <a href="{% url 'crm:contact' contact.id%}">{{ contact.full_name}}</a> <b>Email</b>: {{contact.email}}</li>
            {% endfor %}
              </ol>
            {% else %}
              <p>No contact's found</p>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div id="menu2" class="tab-pane fade">
      <br>
      <a href="{% url 'crm:new_activity'%}" class="btn btn-s btn-success">{{ "Create new activity" }}</a>
          <br>
      <br>
      <div class="col-md-9 ">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">{{ client.name }} activitites</h3>
    </div>

      <div class="panel-body">
      {% if client.activity_set.all %}
        <table id="contacts_table" class="table table-striped">
          <thead>
            <tr>
              <th>Client</th>
              <th>Title</th>
              <th>Contact</th>
              <th>Send date</th>
              <th>More info</th>

            </tr>
          </thead>
          <tbody>
            {% for activity in client.activity_set.all %}
            <tr>
              <td><a href="{% url 'crm:client' activity.client.id%}">{{ activity.client.name }}</a></td>
              <td> {{ activity.title }}</td>
              <td><a href="{% url 'crm:contact' activity.contact.id%}">{{ activity.contact.email }}</a></td>
              <td> {{ activity.send_date|date:"Y.m.d H:i"}}</td>
              <td><a href="{% url 'crm:activity' activity.id%}">Show</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
      <p>No activities found</p>
      {% endif %}
    </div>
  </div>
          </div>
      </div>
    </div>
{% else %}
<h3>You don't have rights to view this client</h3>
{% endif %}
{% endblock content %}

dive_into/crm/templates/crm/clients.html
{% extends 'crm/base.html' %}
{% block content %}


<p><a class="btn btn-xs btn-success" href="{% url 'crm:new_client'%}" >{{ "Create new client" }}</a></p>

<div class="col-md-9 ">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">All clients</h3>
    </div>
    <div class="panel-body">
      {% if clients_list %}
      <!-- Таблица всех контактов в системе -->
        <table id="contacts_table" class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Loyal</th>
              <th>Activities</th>
              <th>Last activity date</th>
              <th>Contacts</th>
            </tr>
          </thead>
          <tbody>
            {% for client in clients_list %}
            <tr>
              <td><a href="{% url 'crm:client' client.id%}">{{ client.name }}</a></td>
              <td> {{ client.loyal}}</td>
              <td> {{ client.activity_set.count}}</td>
              <td> {{ client.last_activity}}</td>
              <td> {{ client.contact_set.count}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

      {% else %}
      <p>No clients are available.</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}

dive_into/crm/templates/crm/contact_detail.html
{% extends 'crm/base.html' %}
{% block content %}
{% load bootstrap %}
{% if contact %}
  <button class="btn btn-s btn-info" data-toggle="collapse" data-target="#hide-me">Change contact</button>
{% if contact.client %}
  <a href="{% url 'crm:client' contact.client.id%}" class="btn btn-s btn-info">{{ "Go to client" }}</a>
{% endif %}
<!-- Форма для удаления контакта -->
<form  method="post">
   {% csrf_token %}
   <input id="action_id" type="hidden" name="action" value="Delete">
   <input type="submit" value="Delete" class="btn btn-s btn-danger" onclick="return confirm('Are you sure?')"/>
</form>
<div id="hide-me" class="collapse">
   <!-- Форма для изменения контакта -->

   <form method="post" class="form-horizontal">
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
         <div class="col-sm-10 col-sm-offset-2">
            <input type="submit" value="Save changes" class="btn btn-s btn-success">
         </div>
      </div>
   </form>
</div>
{% for a,b in form.errors.items %}
  <div class="alert alert-danger custom-alert" role="alert">
    <strong>Warning!</strong> {{b}} You should correct the mistakes and then save changes again
  </div>
{% endfor %}

<h3>Contact</h3>
<blockquote>
   {{contact.str_with_html|safe|linebreaks}}
</blockquote>
{% else %}
  <h3>You don't have rights to view this contact</h3>
{% endif %}
{% endblock content %}

dive_into/crm/templates/crm/contacts.html
{% extends 'crm/base.html' %}
{% block content %}
<p><a class="btn btn-xs btn-success"  href="{% url 'crm:new_contact'%}">{{ "Create new contact" }}</a></p>

<div class="col-md-9 ">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Table of contacts</h3>
    </div>
    <div class="panel-body">
      {% if contacts_list %}
      <!-- Таблица всех контактов в системе -->
        <table id="contacts_table" class="table table-striped">
          <thead>
            <tr>
              <th>First name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Active</th>
              <th>Client</th>
            </tr>
          </thead>
          <tbody>
            {% for contact in contacts_list %}
            <tr>
              <td><a href="{% url 'crm:contact' contact.id%}">{{ contact.first_name }}</a></td>
              <td> {{ contact.last_name }}</td>
              <td> {{ contact.email }}</td>
              <td> {{ contact.phone }}</td>
              <td> {{ contact.active }}</td>
              <td><a href="{% url 'crm:client' contact.client.id|default:1%}">{{ contact.client.name }}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

      {% else %}
      <p>No contacts are available.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

dive_into/crm/templates/crm/new_client.html
{% extends 'crm/base.html' %}
{% block content %}
{% load bootstrap %}

<h3>{{ "Create new client" }}</h3>

<!-- Форма для создани клиента -->
<form method="post">
  {% csrf_token %}
  {{ form|bootstrap }}
  <input type="submit" value="Create" class="btn btn-s btn-success">
</form>

{% endblock content%}